supports 'fedora' needs to have semver for version
Error: Failed to generate Policyfile.lock
Reason: (Chef::Exceptions::InvalidCookbookVersion) '21' does not match 'x.y.z' or 'x.y'